
- name: Base Image
  hosts: "{{ hosts }}"

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build

    - name: Install pre dependencies
      become: yes
      apt:
        name: "{{ item }}"
      with_items:
        - aptitude
      tags:
        - build

  roles:
    - role: base_image
