---

- include: configure/mysql.yml

- name: Ensure Tomcat config folders
  become: yes
  file:
    dest: "/home/{{ hippo_authoring.user }}/tomcat/{{ item }}"
    group: "{{ hippo_authoring.user }}"
    owner: "{{ hippo_authoring.user }}"
    state: directory
  with_items:
    - conf
    - conf/query
    - conf/query/lucene

- name: Copy config
  become: yes
  template:
    dest: "/home/{{ hippo_authoring.user }}/tomcat/{{ item }}"
    group: "{{ hippo_authoring.user }}"
    owner: "{{ hippo_authoring.user }}"
    src: "{{ item }}.j2"
    mode: u=rw
  with_items:
    - conf/context.xml
    - conf/log4j.xml
    - conf/query/lucene/indexing_configuration.xml
    - conf/repository.xml
    - conf/server.xml
    - conf/tomcat-users.xml

- name: Create tomcat/bin files
  become: yes
  template:
    dest: "/home/{{ hippo_authoring.user }}/tomcat/{{ item }}"
    group: "{{ hippo_authoring.user }}"
    mode: u=rwx
    owner: "{{ hippo_authoring.user }}"
    src: "{{ item }}.j2"
  with_items:
    - bin/setenv.sh
    - bin/shutdown_wrapper.sh
    - bin/startup_wrapper.sh

# Tomcat out of the box comes with ROOT application already deployed and running
# hence the deletion of the "ROOT" folder before deploying "site" as ROOT.war.
- name: Ensure ROOT folder is deleted
  become: yes
  file:
    dest: "/home/{{ hippo_authoring.user }}/tomcat/webapps/ROOT"
    state: absent

- name: Ensure Hippo CMS is running
  become: yes
  service:
    name: "{{ hippo_authoring.user }}"
    state: restarted

- name: Wait for Hippo to wake up
  wait_for:
    delay: 10
    host: 127.0.0.1
    port: 8080
