---

- include: configure/mysql.yml

- include: configure/nginx.yml

- name: Ensure Hippo CMS is running
  become: yes
  service:
    name: "{{ hippo_authoring.user }}"
    state: restarted

- name: Wait for Hippo to wake up
  wait_for:
    delay: 10
    host: 127.0.0.1
    port: 8080

- name: Ensure Nginx proxy is running
  become: yes
  service:
    name: nginx
    state: restarted

- name: Wait for Nginx Proxy
  wait_for:
    delay: 1
    host: 127.0.0.1
    port: 80
