---

- name: "Copy local Hippo .artefacts/hippo_authoring-{{ hippo_authoring.version }}.tgz"
  become: yes
  copy:
    dest: "/tmp/hippo_authoring-{{ hippo_authoring.version }}.tgz"
    group: "{{ hippo_authoring.user }}"
    owner: "{{ hippo_authoring.user }}"
    src: "{{ root_dir }}/../.artefacts/hippo_authoring-{{ hippo_authoring.version }}.tgz"
