
- name: Ensure Hippo CMS environment
  hosts: "{{ hosts }}"

  vars_files:
    - "{{ playbook_dir }}/defaults/main.yml"

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build

  roles:
    - role: sansible.mysql
      mysql:
        version: 5.7
        root_user: "{{ hippo_delivery.mysql.root_user }}"
        root_password: "{{ hippo_delivery.mysql.root_password }}"
