---

base_image:
  # Vagrant specific
  vm:
    cores: 1
    memory: 512
    priv_ip: 192.168.50.11
    hosts: [ ]

hippo_authoring:
  # Vagrant specific
  vm:
    cores: 1
    memory: 2048
    priv_ip: 192.168.50.10
    hosts:
      - hippo-authoring.int
      - hippo-authoring.mysql.db.int

  # Ansible role specific
  domain: hippo-authoring.nhsd-ps.int

  source:
    type: local

hippo_delivery:
  # Vagrant specific
  vm:
    cores: 1
    memory: 2048
    priv_ip: 192.168.50.11
    hosts:
      - hippo-delivery.int

  # Ansible role specific
  domain: hippo-delivery.int

  mysql:
    # hippo_authoring Mysql
    host: 192.168.50.10

  source:
    type: local
