
base_image:
  # Vagrant specific
  vm:
    cores: 1
    memory: 512
    priv_ip: 192.168.50.11
    hosts: [ ]

hippocms:
  # Vagrant specific
  vm:
    cores: 1
    memory: 2048
    priv_ip: 192.168.50.10
    hosts:
      - hippocms.nhsd-ps.int
      - cms.hippocms.nhsd-ps.int

  # Ansible role specific
  domains:
    site: hippocms.nhsd-ps.int
    cms: cms.hippocms.nhsd-ps.int
