---

base_image:
  # Vagrant specific
  vm:
    cores: 1
    memory: 512
    priv_ip: 192.168.50.11
    hosts: [ ]

hippo_authoring:
  # Vagrant specific
  vm:
    cores: 1
    memory: 2048
    priv_ip: 192.168.50.10
    hosts:
      - hippo-authoring.nhsd-ps.int

  # Ansible role specific
  domain: hippo-authoring.nhsd-ps.int

hippo_delivery:
  # Vagrant specific
  vm:
    cores: 1
    memory: 2048
    priv_ip: 192.168.50.11
    hosts:
      - hippo-delivery.nhsd-ps.int

  # Ansible role specific
  domain: hippo-delivery.nhsd-ps.int
