---

- name: Ensure Tomcat base directories
  become: yes
  file:
    group: "{{ hippo_delivery.user }}"
    mode: u=rwx
    name: "/home/{{ hippo_delivery.user }}/{{ item }}"
    owner: "{{ hippo_delivery.user }}"
    state: directory
  with_items:
    - tomcat-endorsed
    - heapdumps

- name: "download Tomcat {{ hippo_delivery.tomcat.version }} release"
  get_url:
    dest: "/tmp/apache-tomcat-{{ hippo_delivery.tomcat.version }}.tar.gz"
    url: "http://artfiles.org/apache.org/tomcat/tomcat-8/v{{ hippo_delivery.tomcat.version }}/bin/apache-tomcat-{{ hippo_delivery.tomcat.version }}.tar.gz"

- name: "Unpack Tomcat {{ hippo_delivery.tomcat.version }} release"
  become: yes
  unarchive:
    dest: "/home/{{ hippo_delivery.user }}/"
    group: "{{ hippo_delivery.user }}"
    owner: "{{ hippo_delivery.user }}"
    remote_src: yes
    src: "/tmp/apache-tomcat-{{ hippo_delivery.tomcat.version }}.tar.gz"

- name: Ensure Tomcat folder permissions
  become: yes
  file:
    dest: "/home/{{ hippo_delivery.user }}/apache-tomcat-{{ hippo_delivery.tomcat.version }}"
    group: "{{ hippo_delivery.user }}"
    owner: "{{ hippo_delivery.user }}"
    state: directory

- name: Symlink Tomcat
  become: yes
  file:
    dest: "/home/{{ hippo_delivery.user }}/tomcat"
    group: "{{ hippo_delivery.user }}"
    owner: "{{ hippo_delivery.user }}"
    src: "/home/{{ hippo_delivery.user }}/apache-tomcat-{{ hippo_delivery.tomcat.version }}"
    state: link

- name: Download Hippocms dependencies jars
  become: yes
  get_url:
    url: "{{ item.url }}"
    dest: "/home/{{ hippo_delivery.user }}/tomcat-endorsed/{{ item.dest }}"
  with_items:
    - url: http://search.maven.org/remotecontent?filepath=javax/jcr/jcr/2.0/jcr-2.0.jar
      dest: jcr-2.0.jar
    - url: http://search.maven.org/remotecontent?filepath=javax/mail/mail/1.4.7/mail-1.4.7.jar
      dest: mail-1.4.7.jar
    - url: http://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/5.1.36/mysql-connector-java-5.1.36.jar
      dest: mysql-connector-java-5.1.36.jar
    - url: http://search.maven.org/remotecontent?filepath=org/apache/geronimo/specs/geronimo-jta_1.1_spec/1.1/geronimo-jta_1.1_spec-1.1.jar
      dest: geronimo-jta_1.1_spec-1.1.jar

- name: Allow acess to RMI
  become: yes
  blockinfile:
    dest: "/home/{{ hippo_delivery.user }}/tomcat/conf/catalina.policy"
    block: |
      grant codeBase "jar:file:${catalina.home}/webapps/" {
        permission java.net.SocketPermission "*:1099", "connect, accept, listen";
      };

- name: Ensure shared loader paths
  become: yes
  lineinfile:
    dest: "/home/{{ hippo_delivery.user }}/tomcat/conf/catalina.properties"
    line: shared.loader=${catalina.base}/shared/lib,${catalina.base}/shared/lib/*.jar
    regexp: "^shared.loader="

- name: Create tomcat/bin files
  become: yes
  template:
    dest: "/home/{{ hippo_delivery.user }}/tomcat/{{ item }}"
    group: "{{ hippo_delivery.user }}"
    mode: u=rwx
    owner: "{{ hippo_delivery.user }}"
    src: "{{ item }}.j2"
  with_items:
    - bin/setenv.sh
    - bin/shutdown_wrapper.sh
    - bin/startup_wrapper.sh

- name: Create env file with Tomcat manager user creds
  become: yes
  template:
    dest: "/home/{{ hippo_delivery.user }}/.hippo-manager-env"
    group: "{{ hippo_delivery.user }}"
    mode: u=rw,o=,g=
    owner: "{{ hippo_delivery.user }}"
    src: "hippo-manager-env.j2"

- name: Create Systemd service
  become: yes
  template:
    dest: "/etc/systemd/system/{{ hippo_delivery.user }}.service"
    mode: u=rw,g=r,o=r
    src: systemd/hippo_delivery.service.j2

- name: Register service
  service:
    enabled: no
    name: "{{ hippo_delivery.user }}"

# Allow "hippo_delivery" user to operate hippo_delivery service
- name: Create sudoers config
  become: yes
  template:
    dest: /etc/sudoers.d/hippo_delivery
    mode: u=rw,o=r,g=r
    src: sudoers.d/hippo_delivery.j2

##
# Download and unpack Hippo CMS
#
- name: Get the source of the Hippo delivery (site)
  include: "source_{{ hippo_delivery.source.type }}.yml"
  when: hippo_delivery.source.type

- name: Unarchive hippocms
  become: yes
  unarchive:
    dest: "/home/{{ hippo_delivery.user }}/tomcat"
    extra_opts:
      - common
      - shared
      - webapps
    group: "{{ hippo_delivery.user }}"
    owner: "{{ hippo_delivery.user }}"
    remote_src: yes
    src: /tmp/hippo_delivery-{{ hippo_delivery.version }}.tgz
