---

- name: Copy config
  become: yes
  template:
    dest: "/home/{{ hippo_delivery.user }}/tomcat/{{ item }}"
    group: "{{ hippo_delivery.user }}"
    owner: "{{ hippo_delivery.user }}"
    src: "{{ item }}.j2"
    mode: u=rw
  with_items:
    - conf/context.xml
    - conf/log4j.xml
    - conf/repository.xml
    - conf/tomcat-users.xml

# Tomcat out of the box comes with ROOT application already deployed and running
# hence the deletion of the "ROOT" folder before deploying "site" as ROOT.war.
- name: Ensure ROOT folder is deleted
  become: yes
  file:
    dest: "/home/{{ hippo_delivery.user }}/tomcat/webapps/ROOT"
    state: absent

- name: Ensure Hippo CMS is running
  become: yes
  service:
    name: "{{ hippo_delivery.user }}"
    state: restarted

- name: Wait for Hippo to wake up
  wait_for:
    delay: 10
    host: 127.0.0.1
    port: 8080
