---

- name: AMI Build
  hosts: "{{ hosts }}"
  gather_facts: no

  pre_tasks:
    - name: Assert global variable are set
      assert:
        that:
          - role is defined
      tags:
        - build

    - name: Load build artefact
      include_vars: "{{ playbook_dir }}/../../.artefacts/{{ role }}.yml"
      when: role in [ 'hippo_authoring', 'hippo_delivery' ]
      tags:
        - build

    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      register: result
      until: result | succeeded
      retries: 18
      delay: 10
      tags:
        - build

  roles:
    - role: "{{ role }}"

- name: Ensure common roles
  hosts: "{{ hosts }}"

  pre_tasks:
    - name: Delete current bootstrap folder
      become: yes
      file:
        path: /bootstrap
        state: absent
      tags:
        - build

  roles:
    - role: ansible-city.aws_bootstrap
      aws_bootstrap:
        teleport_mode: standard
        extras:
          - mysql
