---

- name: Ensure Proxy config
  become: yes
  template:
    src: nginx/hippocms.j2
    dest: /etc/nginx/sites-available/hippocms

- name: Ensure site symlink
  become: yes
  file:
    state: link
    src: /etc/nginx/sites-available/hippocms
    dest: /etc/nginx/sites-enabled/hippocms
