---

hippo_authoring:
  user: hippo_authoring
  domain: hippo_authoring
  # how to deploy / download Hippo
  # - internal
  # - local
  # - s3
  deploy_type: ~
  manager_password: hippo

  java:
    version: 8

  mysql:
    root_user: root
    root_password: changeme!
    user: hippocms
    password: changeme!hippocms
    dbname: hippocms

  tomcat:
    version: "8.0.46"
