---

dependencies:
  - role: sansible.users_and_groups
    users_and_groups:
      users:
        - name: "{{ hippo_delivery.user }}"

  - role: sansible.java
    java:
      version: "{{ hippo_delivery.java.version }}"

  - role: sansible.nginx
